### ISSUE TITLE
Add page system

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/library#25]
`View of: [25^]`

> When loading the database (.json) the website starts to demand too much resources, making the browser not work properly and making it impossible to edit the opcodes.
>
> Maybe if it is saved in the browser's cache it will help a little, but maybe it will help even more if a paging system is put in place :)

`[1] [2] ... [<] [55] [>] ... [232] [233]`

**Comment by x87** [comment]
makes sense. thanks for the idea
