### ISSUE TITLE
minimize risk of losing or overwriting changes made by different editors

### ISSUE THREAD

**Issue by x87** [sannybuilder/library#37]
@wmysterio @XMDS @MatiDragon-YT 

I see we keep rewriting each others work. I will take a look into changing the editor so it pulls the latest library snapshot just before the submit to github to reduce the risk of losing changes that were made already by another person.

_Originally posted by @x87 in https://github.com/sannybuilder/dev/discussions/136#discussioncomment-681130_

**Comment by x87** [comment]
- [x] pull latest changes before submit
   - [ ] consider increasing fuzzFactor from 500 to a larger number (3000?)
- [ ] (auth only) ping server every 5 minutes and after doing a change(?) to check if there is an update
  - [ ] check if local changes could be applied to the recent version, and if yes, offer an update of local state
     - [ ] regardless of the choice, always check for update before submitting 
  - [ ] if the patch is not possible, submit changes in a separate branch and create a pull request for manual resolution
  - [ ] optionally implement a hibernate time when the user is not active
- [ ] patch non-extension files

**Comment by wmysterio** [comment]
>  if merge is not possible, submit changes in a merge request for manual resolution

Merging should help in many cases. I would like to have this feature in the arsenal.

**Comment by x87** [comment]
due to the low activity and rare edit clashes this issue is no longer in consideration.
