### ISSUE TITLE
add property *download* to links

### ISSUE THREAD

**Issue by MatiDragon-YT** [sannybuilder/library#45]
For not open the file in the browser.
```
<a ... >enums.txt</a>
```
indicate that it is a downloadable file:
```
<a ...  download>enums.txt</a>
```

**Comment by x87** [comment]
Want to try adding them? I can guide you

**Comment by MatiDragon-YT** [comment]
I am someone who gets lost very easily...

---

at my [library-master.zip of 30/05/2021](https://github.com/sannybuilder/library/files/6625272/library-master.zip)

in `\library-master\editor\src\app\components\layout\download-panel\download-panel.component.html`
I don't know if the location is still the same, but I found the file that generates the download block:
```html
<div class="card mb-3">
  <div class="card-body flex-column">
    <h5 class="mb-3">{{ "ui.layout.downloads" | translate }}</h5>
    <ul class="nav navbar-dark flex-row flex-xl-column">
      <li class="pr-2">
        <a [href]="getClasses(game)" target="_blank">classes.db</a>
      </li>
      <li class="pr-2">
        <a [href]="getEnums(game)" target="_blank">enums.txt</a>
      </li>
    </ul>
  </div>
</div>
```
I replace it with this: 
```html
<div class="card mb-3">
  <div class="card-body flex-column">
    <h5 class="mb-3">{{ "ui.layout.downloads" | translate }}</h5>
    <ul class="nav navbar-dark flex-row flex-xl-column">
      <li class="pr-2">
        <a [href]="getClasses(game)" target="_blank">classes.db</a>
      </li>
      <li class="pr-2">
        <a [href]="getEnums(game)" target="_blank" download>enums.txt</a>
      </li>
    </ul>
  </div>
</div>
```

**Comment by x87** [comment]
What I mean is opening an actual pull request ready to be merged. This is a simple enough change where you can train and go through the process.

You can follow this guide for all necessary steps: https://sannybuilder.com/dev/making-a-pull-request.pdf
(this guide is for making changes in https://github.com/sannybuilder/data but in our case the target is https://github.com/sannybuilder/library)
