### ISSUE TITLE
command keywords editor

### ISSUE THREAD

**Issue by XMDS** [sannybuilder/library#48]
Currently in non-SCR mode, the keyword file of the corresponding game needs to be updated.

Need to provide the download of the keyword file on the online website.
In the SBL editor, when the command attribute is marked as ``is_keyword``, it is hoped that the corresponding keyword can be automatically added to the keyword file after submission.
And the function of adding multiple keyword forms should be implemented in the online editor, for example, a command supports multiple keyword writing:

```
004E=end_thread  //old shorthand
004E=terminate_this_script //standard
004E=end_script //New shorthand
```
The main purpose is to retain the old keyword format, while the submitter can add a new, easy-to-write keyword format in the editor.

**Comment by XMDS** [comment]
In addition, when commanding the query preview.  The multiple keyword forms of the command should also be displayed on the online website (if there are multiple)

**Comment by x87** [comment]
>provide the download of the keyword file on the online website.

this is done

**Comment by x87** [comment]
closing as adding multiple keywords per command does not sound reasonable: just bloats the language.
