### ISSUE TITLE
Can't download vc_classic/enums.txt

### ISSUE THREAD

**Issue by NicusorN5** [sannybuilder/library#52]
Trying to open `https://library.sannybuilder.com/assets/vc_classic/enums.txt` redirects me to `https://library.sannybuilder.com/#`

Is this a problem on  my side? I was able to download the other 2 files: `classes.db` and `keywords.txt`

**Comment by x87** [comment]
Thanks for reporting. Fixed via cc889f9

**Comment by NicusorN5** [comment]
Thank you!
