### ISSUE TITLE
error in 08EC

### ISSUE THREAD

**Issue by x87** [sannybuilder/library#73]
https://library.sannybuilder.com/#/sa/default/08EC has an issue in description

Returns the class="param-name">vehicle's class as defined in vehicles.ide

**Comment by OrionSR** [comment]
My suspicion is that the word "class" in the description is causing the formatting issue. I had a similar issue with the word "param" in a short description, and rephrased that description to avoid the issue.

**Comment by x87** [comment]
issue is somewhere here https://github.com/sannybuilder/library/blob/master/editor/src/app/pipes/linkify.pipe.ts

**Comment by x87** [comment]
I guess when there are multiple params it gets into trouble in this loop
https://github.com/sannybuilder/library/blob/c4745dc439bdd850477c383db644f119b4b3b503/editor/src/app/pipes/linkify.pipe.ts#L74

when the previous param was already wrapped in `<span class="param-name">$&</span>` it becomes a part of description line

**Comment by x87** [comment]
fixed in a432e5e67fadd92c7b856cbfe418a8adcc1f001c
